name: Auto-merge

on:
  workflow_call:
    inputs:
      pr_url:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  check-and-merge:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      PR_URL: ${{ inputs.pr_url }}
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - name: Checkout repository with preceding commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve
      ## いきなりマージするのが怖いので、一旦自動承認（↑）だけにする
      #- name: Enable auto-merge
      #  run: gh pr merge --merge --auto "$PR_URL"

  failed:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: failed
        env:
          WORKFLOW_RUN_CONTEXT: ${{ toJson(github.event.workflow_run) }}
        # 失敗したときにデバッグ用に情報を出力しておく
        run: |
          echo "Haven't met the conditions to merge yet"
          echo "$WORKFLOW_RUN_CONTEXT"
          exit 1
