name: Pull Request review approved

on:
  pull_request_review:
    typees: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    permissions:
      pull-requests: write
      contents: write
    uses: ./.github/workflows/auto-merge.yml
    with:
      pr_url: ${{github.event.pull_request.html_url}}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
